# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/irasin/desktop/mindspore/mindspore/lite/nnacl/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/irasin/desktop/mindspore/mindspore/lite/nnacl/optimize/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/irasin/desktop/mindspore/mindspore/lite/xcode-build/CMakeFiles/3.19.3/CMakeASMCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeASMCompiler.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeASMInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeCompilerIdDetection.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeDetermineASMCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeDetermineCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeDetermineCompilerId.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeFindBinUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/CMakeTestASMCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/Compiler/Clang-ASM.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/Compiler/Clang-FindBinUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/Platform/Apple-Clang-ASM.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/Platform/Apple-Clang.cmake))

/Users/irasin/desktop/mindspore/mindspore/lite/xcode-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -H/Users/irasin/desktop/mindspore/mindspore/lite -B/Users/irasin/desktop/mindspore/mindspore/lite/xcode-build
